application: github-malu-me
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: public/index.php

- url: /(.+)
  script: public/\1

- url: /img/(.+)
  static_files: public/img/\1
  upload: public/img/(.*)